blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discord Community
    url: https://discord.gg/uqMwZvXHBE
    about: Join our Discord for quick help and community discussions!
  - name: ğŸ“š Documentation
    url: https://github.com/Computer-Science-Girlies/cs-girlies-guides
    about: Check out our documentation for guides and resources
  - name: ğŸ’ Donate
    url: https://www.csgirlies.com/donate
    about: Support CS Girlies by making a donation
  - name: ğŸŒ Website
    url: https://csgirlies.com
    about: Visit our website for more information
